// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGvaAutQbMCARj_4KcWlS59U1ZJxQPils',
    appId: '1:98924900282:web:2bde9eaabf44ea54f8b783',
    messagingSenderId: '98924900282',
    projectId: 'flutter-masterclass-fa335',
    authDomain: 'flutter-masterclass-fa335.firebaseapp.com',
    storageBucket: 'flutter-masterclass-fa335.firebasestorage.app',
    measurementId: 'G-F4284CWEMV',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFkxcvX4xfHoFrzGWjLFAuQmWj0kBVzXI',
    appId: '1:98924900282:ios:481cccc2402ceabbf8b783',
    messagingSenderId: '98924900282',
    projectId: 'flutter-masterclass-fa335',
    storageBucket: 'flutter-masterclass-fa335.firebasestorage.app',
    iosBundleId: 'com.example.flutterRpg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGvaAutQbMCARj_4KcWlS59U1ZJxQPils',
    appId: '1:98924900282:web:f52b33ea8a1a821ef8b783',
    messagingSenderId: '98924900282',
    projectId: 'flutter-masterclass-fa335',
    authDomain: 'flutter-masterclass-fa335.firebaseapp.com',
    storageBucket: 'flutter-masterclass-fa335.firebasestorage.app',
    measurementId: 'G-DF5CNM3SC1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFkxcvX4xfHoFrzGWjLFAuQmWj0kBVzXI',
    appId: '1:98924900282:ios:481cccc2402ceabbf8b783',
    messagingSenderId: '98924900282',
    projectId: 'flutter-masterclass-fa335',
    storageBucket: 'flutter-masterclass-fa335.firebasestorage.app',
    iosBundleId: 'com.example.flutterRpg',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbK2MBpzjvZAJYlUXE4EOG2Hsu9pHay2Q',
    appId: '1:98924900282:android:60c052bc21d466a0f8b783',
    messagingSenderId: '98924900282',
    projectId: 'flutter-masterclass-fa335',
    storageBucket: 'flutter-masterclass-fa335.firebasestorage.app',
  );

}